name: Build ImmortalWrt-24.10.2 for N1

on:
  workflow_dispatch:
   inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false
  schedule:
    - cron: '0 16 * * 0'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_REF: v24.10.2
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: 检查Actions
      uses: actions/checkout@main

    - name: 释放空间
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: 初始化编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh | sudo bash > /dev/null
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 克隆源码
      working-directory: /workdir
      run: |
        git clone $REPO_URL -b $REPO_REF --single-branch --depth=1 openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: 更新并安装feeds
      working-directory: ./openwrt
      run: |
        chmod +x $GITHUB_WORKSPACE/diy-1.sh
        $GITHUB_WORKSPACE/diy-1.sh
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 加载自定义配置
      working-directory: ./openwrt
      run: |
        chmod +x $GITHUB_WORKSPACE/diy-2.sh
        $GITHUB_WORKSPACE/diy-2.sh
        rm -rf ./files ./.config
        mv "$GITHUB_WORKSPACE/files" ./files
        mv "$GITHUB_WORKSPACE/.config" ./.config 
        
    - name: SSH连接到Actions
      uses: P3TERX/ssh2actions@main
      if: github.event.inputs.ssh == 'true'

    - name: 下载软件包
      working-directory: ./openwrt
      run: |
        make defconfig
        make download -j$(( $(nproc) * 2 ))
        find dl -size -1k -exec ls -l {} \;
        find dl -size -1k -exec rm -f {} \;

    - name: 编译N1固件
      run: |
        chmod -R 755 openwrt
        cd openwrt
        echo -e "可使用的核心数：$(nproc)"
        make -j$(($(nproc) * 3 / 2)) || make -j$(nproc) || make -j$(($(nproc) / 2))
        
    - name: 打包ARM内核
      uses: unifreq/openwrt_packit@master
      env:
        OPENWRT_ARMVIRT: openwrt/bin/targets/armsr/armv8/*rootfs.tar.gz
        OPENWRT_VER: ${{ env.REPO_REF }}
        KERNEL_REPO_URL: breakingbadboy/OpenWrt
        KERNEL_VERSION_NAME: 6.6.y
        PACKAGE_SOC: diy
        GZIP_IMGS: .xz
        SCRIPT_DIY_PATH: mk_s905d_n1.sh
        WHOAMI: Winnie-0721
        SW_FLOWOFFLOAD: 0
        SFE_FLOW: 0
        
    - name: 发布固件
      uses: softprops/action-gh-release@master
      with:
        tag_name: ImmortalWrt_${{ env.PACKAGED_OUTPUTDATE }}
        files: ${{ env.PACKAGED_OUTPUTPATH }}/*.img.xz
        body: |
          首次使用建议全新刷写
          * 基本信息
          默认开启 DHCP
          账户: root
          密码: password

    - name: 删除运行记录
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 3
        keep_minimum_runs: 4
        token: ${{ env.GITHUB_TOKEN }}

    - name: 删除的旧固件
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 2
        delete_tags : true
